# Copyright 2022-2023 Hewlett Packard Enterprise Development LP
name: GitHub Actions CI

on: [push, pull_request]
jobs:
  ci:
    runs-on: self-hosted
    strategy:
      matrix:
        go: [ '1.17' ]
    name: Acceptance Tests(excluding cluster create test)
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install packages
        run: go install github.com/nomad-software/vend@v1.0.3

      - name: Run acceptance tests
        env:
          HPEGL_TENANT_ID:  ${{ secrets.HPEGL_TENANT_ID }}
          HPEGL_USER_ID: ${{ secrets.HPEGL_USER_ID }}
          HPEGL_USER_SECRET: ${{ secrets.HPEGL_USER_SECRET }}
          HPEGL_IAM_SERVICE_URL: ${{ secrets.HPEGL_IAM_SERVICE_URL }}
          TF_VAR_HPEGL_SPACE: ${{ secrets.TF_VAR_HPEGL_SPACE }}
        run: make acceptance-short
